/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl3.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greeting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl3.myDsl.Greeting#getPerson <em>Person</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl3.myDsl.MyDslPackage#getGreeting()
 * @model
 * @generated
 */
public interface Greeting extends Element
{
  /**
	 * Returns the value of the '<em><b>Person</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Person</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Person</em>' reference.
	 * @see #setPerson(Person)
	 * @see org.xtext.example.mydsl3.myDsl.MyDslPackage#getGreeting_Person()
	 * @model
	 * @generated
	 */
  Person getPerson();

  /**
	 * Sets the value of the '{@link org.xtext.example.mydsl3.myDsl.Greeting#getPerson <em>Person</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Person</em>' reference.
	 * @see #getPerson()
	 * @generated
	 */
  void setPerson(Person value);

} // Greeting
