/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydot.myDot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dot Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydot.myDot.DotExpression#getRef <em>Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydot.myDot.DotExpression#getTail <em>Tail</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydot.myDot.MyDotPackage#getDotExpression()
 * @model
 * @generated
 */
public interface DotExpression extends Ref
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(Ref)
   * @see org.xtext.example.mydot.myDot.MyDotPackage#getDotExpression_Ref()
   * @model containment="true"
   * @generated
   */
  Ref getRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydot.myDot.DotExpression#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Ref value);

  /**
   * Returns the value of the '<em><b>Tail</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tail</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tail</em>' reference.
   * @see #setTail(Feature)
   * @see org.xtext.example.mydot.myDot.MyDotPackage#getDotExpression_Tail()
   * @model
   * @generated
   */
  Feature getTail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydot.myDot.DotExpression#getTail <em>Tail</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tail</em>' reference.
   * @see #getTail()
   * @generated
   */
  void setTail(Feature value);

} // DotExpression
