/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydot.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.mydot.ui.internal.MydotActivator;

public class MyDotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydotActivator.getInstance().getInjector("org.xtext.example.mydot.MyDot");
	}

}
