/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link Decorator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LinkDecorator#getInert <em>Inert</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLinkDecorator()
 * @model
 * @generated
 */
public interface LinkDecorator extends EObject
{
  /**
   * Returns the value of the '<em><b>Inert</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Inertia}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inert</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inert</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLinkDecorator_Inert()
   * @model containment="true"
   * @generated
   */
  EList<Inertia> getInert();

} // LinkDecorator
