/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mass</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Mass#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Mass#getMassValueInKilograms <em>Mass Value In Kilograms</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMass()
 * @model
 * @generated
 */
public interface Mass extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Mass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mass Value In Kilograms</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mass Value In Kilograms</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mass Value In Kilograms</em>' attribute.
   * @see #setMassValueInKilograms(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMass_MassValueInKilograms()
   * @model
   * @generated
   */
  int getMassValueInKilograms();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Mass#getMassValueInKilograms <em>Mass Value In Kilograms</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mass Value In Kilograms</em>' attribute.
   * @see #getMassValueInKilograms()
   * @generated
   */
  void setMassValueInKilograms(int value);

} // Mass
