/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RobotImpl <em>Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RobotImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRobot()
   * @generated
   */
  int ROBOT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__NAME = 0;

  /**
   * The feature id for the '<em><b>Topologies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__TOPOLOGIES = 1;

  /**
   * The feature id for the '<em><b>Link</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__LINK = 2;

  /**
   * The feature id for the '<em><b>Joint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__JOINT = 3;

  /**
   * The feature id for the '<em><b>Linkrefs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__LINKREFS = 4;

  /**
   * The number of structural features of the '<em>Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TopologyImpl <em>Topology</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TopologyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTopology()
   * @generated
   */
  int TOPOLOGY = 1;

  /**
   * The feature id for the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPOLOGY__PARENT = 0;

  /**
   * The feature id for the '<em><b>Joint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPOLOGY__JOINT = 1;

  /**
   * The feature id for the '<em><b>Child</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPOLOGY__CHILD = 2;

  /**
   * The number of structural features of the '<em>Topology</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPOLOGY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
   * @generated
   */
  int LINK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NAME = 0;

  /**
   * The feature id for the '<em><b>Is Reuse Of</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__IS_REUSE_OF = 1;

  /**
   * The feature id for the '<em><b>Decorator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__DECORATOR = 2;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkDecoratorImpl <em>Link Decorator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LinkDecoratorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLinkDecorator()
   * @generated
   */
  int LINK_DECORATOR = 3;

  /**
   * The feature id for the '<em><b>Inert</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_DECORATOR__INERT = 0;

  /**
   * The number of structural features of the '<em>Link Decorator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_DECORATOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkRefImpl <em>Link Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LinkRefImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLinkRef()
   * @generated
   */
  int LINK_REF = 4;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_REF__REF = 0;

  /**
   * The feature id for the '<em><b>Decorator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_REF__DECORATOR = 1;

  /**
   * The number of structural features of the '<em>Link Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_REF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.JointImpl <em>Joint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.JointImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJoint()
   * @generated
   */
  int JOINT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT__NAME = 0;

  /**
   * The feature id for the '<em><b>Is Reuse Of</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT__IS_REUSE_OF = 1;

  /**
   * The feature id for the '<em><b>Child Of</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT__CHILD_OF = 2;

  /**
   * The feature id for the '<em><b>Parent Of</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT__PARENT_OF = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT__TYPE = 4;

  /**
   * The number of structural features of the '<em>Joint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.JointRefImpl <em>Joint Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.JointRefImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJointRef()
   * @generated
   */
  int JOINT_REF = 6;

  /**
   * The feature id for the '<em><b>Fix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_REF__FIX = 0;

  /**
   * The feature id for the '<em><b>Rev</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_REF__REV = 1;

  /**
   * The feature id for the '<em><b>Pris</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_REF__PRIS = 2;

  /**
   * The feature id for the '<em><b>Cont</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_REF__CONT = 3;

  /**
   * The number of structural features of the '<em>Joint Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOINT_REF_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InertialImpl <em>Inertial</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InertialImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInertial()
   * @generated
   */
  int INERTIAL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Inertia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIAL__INERTIA = 1;

  /**
   * The feature id for the '<em><b>Mass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIAL__MASS = 2;

  /**
   * The feature id for the '<em><b>Origin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIAL__ORIGIN = 3;

  /**
   * The number of structural features of the '<em>Inertial</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIAL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InertiaImpl <em>Inertia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InertiaImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInertia()
   * @generated
   */
  int INERTIA = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__NAME = 0;

  /**
   * The feature id for the '<em><b>Ixx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__IXX = 1;

  /**
   * The feature id for the '<em><b>Ixy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__IXY = 2;

  /**
   * The feature id for the '<em><b>Ixz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__IXZ = 3;

  /**
   * The feature id for the '<em><b>Iyy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__IYY = 4;

  /**
   * The feature id for the '<em><b>Iyz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__IYZ = 5;

  /**
   * The feature id for the '<em><b>Izz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA__IZZ = 6;

  /**
   * The number of structural features of the '<em>Inertia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INERTIA_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VisualImpl <em>Visual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VisualImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVisual()
   * @generated
   */
  int VISUAL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Origin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUAL__ORIGIN = 1;

  /**
   * The number of structural features of the '<em>Visual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VISUAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CollisionImpl <em>Collision</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CollisionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCollision()
   * @generated
   */
  int COLLISION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLISION__NAME = 0;

  /**
   * The feature id for the '<em><b>Origin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLISION__ORIGIN = 1;

  /**
   * The number of structural features of the '<em>Collision</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLISION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OriginImpl <em>Origin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OriginImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOrigin()
   * @generated
   */
  int ORIGIN = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__NAME = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__Y = 2;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__Z = 3;

  /**
   * The feature id for the '<em><b>Roll</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__ROLL = 4;

  /**
   * The feature id for the '<em><b>Pitch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__PITCH = 5;

  /**
   * The feature id for the '<em><b>Yaw</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN__YAW = 6;

  /**
   * The number of structural features of the '<em>Origin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORIGIN_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MassImpl <em>Mass</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MassImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMass()
   * @generated
   */
  int MASS = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Mass Value In Kilograms</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS__MASS_VALUE_IN_KILOGRAMS = 1;

  /**
   * The number of structural features of the '<em>Mass</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.JointType <em>Joint Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.JointType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJointType()
   * @generated
   */
  int JOINT_TYPE = 13;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Robot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot</em>'.
   * @see org.xtext.example.mydsl.myDsl.Robot
   * @generated
   */
  EClass getRobot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Robot#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Robot#getName()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Robot#getTopologies <em>Topologies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Topologies</em>'.
   * @see org.xtext.example.mydsl.myDsl.Robot#getTopologies()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_Topologies();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Robot#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.Robot#getLink()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_Link();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Robot#getJoint <em>Joint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Joint</em>'.
   * @see org.xtext.example.mydsl.myDsl.Robot#getJoint()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_Joint();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Robot#getLinkrefs <em>Linkrefs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Linkrefs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Robot#getLinkrefs()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_Linkrefs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Topology <em>Topology</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Topology</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topology
   * @generated
   */
  EClass getTopology();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Topology#getParent <em>Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topology#getParent()
   * @see #getTopology()
   * @generated
   */
  EReference getTopology_Parent();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Topology#getJoint <em>Joint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Joint</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topology#getJoint()
   * @see #getTopology()
   * @generated
   */
  EReference getTopology_Joint();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Topology#getChild <em>Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Child</em>'.
   * @see org.xtext.example.mydsl.myDsl.Topology#getChild()
   * @see #getTopology()
   * @generated
   */
  EReference getTopology_Child();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getName()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Link#getIsReuseOf <em>Is Reuse Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Is Reuse Of</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getIsReuseOf()
   * @see #getLink()
   * @generated
   */
  EReference getLink_IsReuseOf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Link#getDecorator <em>Decorator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decorator</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getDecorator()
   * @see #getLink()
   * @generated
   */
  EReference getLink_Decorator();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LinkDecorator <em>Link Decorator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link Decorator</em>'.
   * @see org.xtext.example.mydsl.myDsl.LinkDecorator
   * @generated
   */
  EClass getLinkDecorator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.LinkDecorator#getInert <em>Inert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inert</em>'.
   * @see org.xtext.example.mydsl.myDsl.LinkDecorator#getInert()
   * @see #getLinkDecorator()
   * @generated
   */
  EReference getLinkDecorator_Inert();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LinkRef <em>Link Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link Ref</em>'.
   * @see org.xtext.example.mydsl.myDsl.LinkRef
   * @generated
   */
  EClass getLinkRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.LinkRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.example.mydsl.myDsl.LinkRef#getRef()
   * @see #getLinkRef()
   * @generated
   */
  EReference getLinkRef_Ref();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.LinkRef#getDecorator <em>Decorator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Decorator</em>'.
   * @see org.xtext.example.mydsl.myDsl.LinkRef#getDecorator()
   * @see #getLinkRef()
   * @generated
   */
  EReference getLinkRef_Decorator();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Joint <em>Joint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Joint</em>'.
   * @see org.xtext.example.mydsl.myDsl.Joint
   * @generated
   */
  EClass getJoint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Joint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Joint#getName()
   * @see #getJoint()
   * @generated
   */
  EAttribute getJoint_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Joint#getIsReuseOf <em>Is Reuse Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Is Reuse Of</em>'.
   * @see org.xtext.example.mydsl.myDsl.Joint#getIsReuseOf()
   * @see #getJoint()
   * @generated
   */
  EReference getJoint_IsReuseOf();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Joint#getChildOf <em>Child Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Child Of</em>'.
   * @see org.xtext.example.mydsl.myDsl.Joint#getChildOf()
   * @see #getJoint()
   * @generated
   */
  EReference getJoint_ChildOf();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.Joint#getParentOf <em>Parent Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parent Of</em>'.
   * @see org.xtext.example.mydsl.myDsl.Joint#getParentOf()
   * @see #getJoint()
   * @generated
   */
  EReference getJoint_ParentOf();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Joint#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Joint#getType()
   * @see #getJoint()
   * @generated
   */
  EAttribute getJoint_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.JointRef <em>Joint Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Joint Ref</em>'.
   * @see org.xtext.example.mydsl.myDsl.JointRef
   * @generated
   */
  EClass getJointRef();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.JointRef#getFix <em>Fix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fix</em>'.
   * @see org.xtext.example.mydsl.myDsl.JointRef#getFix()
   * @see #getJointRef()
   * @generated
   */
  EAttribute getJointRef_Fix();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.JointRef#getRev <em>Rev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rev</em>'.
   * @see org.xtext.example.mydsl.myDsl.JointRef#getRev()
   * @see #getJointRef()
   * @generated
   */
  EAttribute getJointRef_Rev();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.JointRef#getPris <em>Pris</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pris</em>'.
   * @see org.xtext.example.mydsl.myDsl.JointRef#getPris()
   * @see #getJointRef()
   * @generated
   */
  EAttribute getJointRef_Pris();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.JointRef#getCont <em>Cont</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cont</em>'.
   * @see org.xtext.example.mydsl.myDsl.JointRef#getCont()
   * @see #getJointRef()
   * @generated
   */
  EAttribute getJointRef_Cont();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Inertial <em>Inertial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inertial</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertial
   * @generated
   */
  EClass getInertial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertial#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertial#getName()
   * @see #getInertial()
   * @generated
   */
  EAttribute getInertial_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Inertial#getInertia <em>Inertia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inertia</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertial#getInertia()
   * @see #getInertial()
   * @generated
   */
  EReference getInertial_Inertia();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Inertial#getMass <em>Mass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mass</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertial#getMass()
   * @see #getInertial()
   * @generated
   */
  EReference getInertial_Mass();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Inertial#getOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Origin</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertial#getOrigin()
   * @see #getInertial()
   * @generated
   */
  EReference getInertial_Origin();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Inertia <em>Inertia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inertia</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia
   * @generated
   */
  EClass getInertia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getName()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getIxx <em>Ixx</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ixx</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getIxx()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Ixx();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getIxy <em>Ixy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ixy</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getIxy()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Ixy();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getIxz <em>Ixz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ixz</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getIxz()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Ixz();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getIyy <em>Iyy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iyy</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getIyy()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Iyy();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getIyz <em>Iyz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iyz</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getIyz()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Iyz();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Inertia#getIzz <em>Izz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Izz</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inertia#getIzz()
   * @see #getInertia()
   * @generated
   */
  EAttribute getInertia_Izz();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Visual <em>Visual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Visual</em>'.
   * @see org.xtext.example.mydsl.myDsl.Visual
   * @generated
   */
  EClass getVisual();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Visual#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Visual#getName()
   * @see #getVisual()
   * @generated
   */
  EAttribute getVisual_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Visual#getOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Origin</em>'.
   * @see org.xtext.example.mydsl.myDsl.Visual#getOrigin()
   * @see #getVisual()
   * @generated
   */
  EReference getVisual_Origin();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Collision <em>Collision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collision</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collision
   * @generated
   */
  EClass getCollision();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Collision#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collision#getName()
   * @see #getCollision()
   * @generated
   */
  EAttribute getCollision_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Collision#getOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Origin</em>'.
   * @see org.xtext.example.mydsl.myDsl.Collision#getOrigin()
   * @see #getCollision()
   * @generated
   */
  EReference getCollision_Origin();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Origin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Origin</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin
   * @generated
   */
  EClass getOrigin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getName()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getX()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getY()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_Y();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getZ <em>Z</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Z</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getZ()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_Z();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getRoll <em>Roll</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Roll</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getRoll()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_Roll();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getPitch <em>Pitch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pitch</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getPitch()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_Pitch();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Origin#getYaw <em>Yaw</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Yaw</em>'.
   * @see org.xtext.example.mydsl.myDsl.Origin#getYaw()
   * @see #getOrigin()
   * @generated
   */
  EAttribute getOrigin_Yaw();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Mass <em>Mass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mass</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mass
   * @generated
   */
  EClass getMass();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mass#getName()
   * @see #getMass()
   * @generated
   */
  EAttribute getMass_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Mass#getMassValueInKilograms <em>Mass Value In Kilograms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mass Value In Kilograms</em>'.
   * @see org.xtext.example.mydsl.myDsl.Mass#getMassValueInKilograms()
   * @see #getMass()
   * @generated
   */
  EAttribute getMass_MassValueInKilograms();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.JointType <em>Joint Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Joint Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.JointType
   * @generated
   */
  EEnum getJointType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RobotImpl <em>Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RobotImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRobot()
     * @generated
     */
    EClass ROBOT = eINSTANCE.getRobot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

    /**
     * The meta object literal for the '<em><b>Topologies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__TOPOLOGIES = eINSTANCE.getRobot_Topologies();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__LINK = eINSTANCE.getRobot_Link();

    /**
     * The meta object literal for the '<em><b>Joint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__JOINT = eINSTANCE.getRobot_Joint();

    /**
     * The meta object literal for the '<em><b>Linkrefs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__LINKREFS = eINSTANCE.getRobot_Linkrefs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TopologyImpl <em>Topology</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TopologyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTopology()
     * @generated
     */
    EClass TOPOLOGY = eINSTANCE.getTopology();

    /**
     * The meta object literal for the '<em><b>Parent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOPOLOGY__PARENT = eINSTANCE.getTopology_Parent();

    /**
     * The meta object literal for the '<em><b>Joint</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOPOLOGY__JOINT = eINSTANCE.getTopology_Joint();

    /**
     * The meta object literal for the '<em><b>Child</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOPOLOGY__CHILD = eINSTANCE.getTopology_Child();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__NAME = eINSTANCE.getLink_Name();

    /**
     * The meta object literal for the '<em><b>Is Reuse Of</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK__IS_REUSE_OF = eINSTANCE.getLink_IsReuseOf();

    /**
     * The meta object literal for the '<em><b>Decorator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK__DECORATOR = eINSTANCE.getLink_Decorator();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkDecoratorImpl <em>Link Decorator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LinkDecoratorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLinkDecorator()
     * @generated
     */
    EClass LINK_DECORATOR = eINSTANCE.getLinkDecorator();

    /**
     * The meta object literal for the '<em><b>Inert</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK_DECORATOR__INERT = eINSTANCE.getLinkDecorator_Inert();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkRefImpl <em>Link Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LinkRefImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLinkRef()
     * @generated
     */
    EClass LINK_REF = eINSTANCE.getLinkRef();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK_REF__REF = eINSTANCE.getLinkRef_Ref();

    /**
     * The meta object literal for the '<em><b>Decorator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK_REF__DECORATOR = eINSTANCE.getLinkRef_Decorator();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.JointImpl <em>Joint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.JointImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJoint()
     * @generated
     */
    EClass JOINT = eINSTANCE.getJoint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT__NAME = eINSTANCE.getJoint_Name();

    /**
     * The meta object literal for the '<em><b>Is Reuse Of</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT__IS_REUSE_OF = eINSTANCE.getJoint_IsReuseOf();

    /**
     * The meta object literal for the '<em><b>Child Of</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT__CHILD_OF = eINSTANCE.getJoint_ChildOf();

    /**
     * The meta object literal for the '<em><b>Parent Of</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOINT__PARENT_OF = eINSTANCE.getJoint_ParentOf();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT__TYPE = eINSTANCE.getJoint_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.JointRefImpl <em>Joint Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.JointRefImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJointRef()
     * @generated
     */
    EClass JOINT_REF = eINSTANCE.getJointRef();

    /**
     * The meta object literal for the '<em><b>Fix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT_REF__FIX = eINSTANCE.getJointRef_Fix();

    /**
     * The meta object literal for the '<em><b>Rev</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT_REF__REV = eINSTANCE.getJointRef_Rev();

    /**
     * The meta object literal for the '<em><b>Pris</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT_REF__PRIS = eINSTANCE.getJointRef_Pris();

    /**
     * The meta object literal for the '<em><b>Cont</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOINT_REF__CONT = eINSTANCE.getJointRef_Cont();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InertialImpl <em>Inertial</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InertialImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInertial()
     * @generated
     */
    EClass INERTIAL = eINSTANCE.getInertial();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIAL__NAME = eINSTANCE.getInertial_Name();

    /**
     * The meta object literal for the '<em><b>Inertia</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INERTIAL__INERTIA = eINSTANCE.getInertial_Inertia();

    /**
     * The meta object literal for the '<em><b>Mass</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INERTIAL__MASS = eINSTANCE.getInertial_Mass();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INERTIAL__ORIGIN = eINSTANCE.getInertial_Origin();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InertiaImpl <em>Inertia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InertiaImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInertia()
     * @generated
     */
    EClass INERTIA = eINSTANCE.getInertia();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__NAME = eINSTANCE.getInertia_Name();

    /**
     * The meta object literal for the '<em><b>Ixx</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__IXX = eINSTANCE.getInertia_Ixx();

    /**
     * The meta object literal for the '<em><b>Ixy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__IXY = eINSTANCE.getInertia_Ixy();

    /**
     * The meta object literal for the '<em><b>Ixz</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__IXZ = eINSTANCE.getInertia_Ixz();

    /**
     * The meta object literal for the '<em><b>Iyy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__IYY = eINSTANCE.getInertia_Iyy();

    /**
     * The meta object literal for the '<em><b>Iyz</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__IYZ = eINSTANCE.getInertia_Iyz();

    /**
     * The meta object literal for the '<em><b>Izz</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INERTIA__IZZ = eINSTANCE.getInertia_Izz();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VisualImpl <em>Visual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VisualImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVisual()
     * @generated
     */
    EClass VISUAL = eINSTANCE.getVisual();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VISUAL__NAME = eINSTANCE.getVisual_Name();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VISUAL__ORIGIN = eINSTANCE.getVisual_Origin();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CollisionImpl <em>Collision</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CollisionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCollision()
     * @generated
     */
    EClass COLLISION = eINSTANCE.getCollision();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLISION__NAME = eINSTANCE.getCollision_Name();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLISION__ORIGIN = eINSTANCE.getCollision_Origin();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OriginImpl <em>Origin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OriginImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOrigin()
     * @generated
     */
    EClass ORIGIN = eINSTANCE.getOrigin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__NAME = eINSTANCE.getOrigin_Name();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__X = eINSTANCE.getOrigin_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__Y = eINSTANCE.getOrigin_Y();

    /**
     * The meta object literal for the '<em><b>Z</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__Z = eINSTANCE.getOrigin_Z();

    /**
     * The meta object literal for the '<em><b>Roll</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__ROLL = eINSTANCE.getOrigin_Roll();

    /**
     * The meta object literal for the '<em><b>Pitch</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__PITCH = eINSTANCE.getOrigin_Pitch();

    /**
     * The meta object literal for the '<em><b>Yaw</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORIGIN__YAW = eINSTANCE.getOrigin_Yaw();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MassImpl <em>Mass</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MassImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMass()
     * @generated
     */
    EClass MASS = eINSTANCE.getMass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MASS__NAME = eINSTANCE.getMass_Name();

    /**
     * The meta object literal for the '<em><b>Mass Value In Kilograms</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MASS__MASS_VALUE_IN_KILOGRAMS = eINSTANCE.getMass_MassValueInKilograms();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.JointType <em>Joint Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.JointType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getJointType()
     * @generated
     */
    EEnum JOINT_TYPE = eINSTANCE.getJointType();

  }

} //MyDslPackage
