/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Origin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getZ <em>Z</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getRoll <em>Roll</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getPitch <em>Pitch</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Origin#getYaw <em>Yaw</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin()
 * @model
 * @generated
 */
public interface Origin extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Y</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Z</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' attribute.
   * @see #setZ(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_Z()
   * @model
   * @generated
   */
  int getZ();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getZ <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Z</em>' attribute.
   * @see #getZ()
   * @generated
   */
  void setZ(int value);

  /**
   * Returns the value of the '<em><b>Roll</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Roll</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roll</em>' attribute.
   * @see #setRoll(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_Roll()
   * @model
   * @generated
   */
  int getRoll();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getRoll <em>Roll</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Roll</em>' attribute.
   * @see #getRoll()
   * @generated
   */
  void setRoll(int value);

  /**
   * Returns the value of the '<em><b>Pitch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pitch</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pitch</em>' attribute.
   * @see #setPitch(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_Pitch()
   * @model
   * @generated
   */
  int getPitch();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getPitch <em>Pitch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pitch</em>' attribute.
   * @see #getPitch()
   * @generated
   */
  void setPitch(int value);

  /**
   * Returns the value of the '<em><b>Yaw</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Yaw</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Yaw</em>' attribute.
   * @see #setYaw(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOrigin_Yaw()
   * @model
   * @generated
   */
  int getYaw();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Origin#getYaw <em>Yaw</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Yaw</em>' attribute.
   * @see #getYaw()
   * @generated
   */
  void setYaw(int value);

} // Origin
