/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydot


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDotStandaloneSetup extends MyDotStandaloneSetupGenerated {

	def static void doSetup() {
		new MyDotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
